const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')
const ts = require('typescript')
const lib = {}
Function('exports', ts.transpile(fs.readFileSync(path.join(__dirname, '../src/lib/contactExport.ts'), 'utf8'), {module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}))(lib)
for (const phone of ['999 888 777', '+51 999888777', '51999888777', '0051 999888777']) assert.equal(lib.normalizeContactPhone(phone), '+51999888777')
for (const phone of ['', '123', '999888777 / 988777666', 'anexo 123', '+51999888', '999+888777']) assert.equal(lib.normalizeContactPhone(phone), null)
assert.equal(lib.normalizeContactPhone('+1 (202) 555-0123'), '+12025550123')
const rows = lib.contactRows([{id:'1',cliente:'José Pérez',telefono:'999888777'},{id:'2',cliente:'José Pérez',telefono:'+51999888777'},{id:'3',cliente:'María',telefono:'123'}])
assert.equal(rows.length,2);assert.equal(rows.filter(row=>row.selected).length,1)
const {text,count} = lib.createContactsVcf(rows)
assert.equal(count,1);assert.match(text,/FN:José Pérez · Mr Fiesta\r\n/);assert.match(text,/TEL;TYPE=CELL:\+51999888777\r\n/)
assert.equal(text.match(/BEGIN:VCARD/g).length,1)
assert.throws(()=>lib.createContactsVcf(rows.map(row=>({...row,selected:false}))))
assert.throws(()=>lib.createContactsVcf([{id:'x',name:'Test',phone:'123',selected:true}]))
const tricky = lib.createContactsVcf([{id:'x',name:'Á'.repeat(100)+';Comma,Slash\\\nTEL:injection',phone:'999888777',selected:true}]).text
assert.ok(tricky.split('\r\n').every(line=>Buffer.byteLength(line)<=75))
const unfolded = tricky.replace(/\r\n /g,'')
assert.match(unfolded,/\\;Comma\\,Slash\\\\\\nTEL:injection/)
assert.equal(unfolded.match(/^TEL:/gm),null)
assert.equal(lib.createContactsVcf([...rows,{...rows[0],id:'copy'}]).count,1)
console.log('PASS: normalization, duplicates, invalid numbers, UTF-8 folding and escaping.')
