import { type FormEvent, type ReactNode, useEffect, useMemo, useState } from 'react'
import { jsPDF } from 'jspdf'
import { CalendarDays, Clipboard, FileText, LoaderCircle, LogOut, MapPin, MessageCircle, Pencil, Save, Trash2, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { AppError } from '../components/AppError'
import { BrandLogo } from '../components/BrandLogo'
import { ToastStack } from '../components/ToastStack'
import { requireSupabase, supabase } from '../lib/supabase'
import type { CrmEvent, ToastMessage } from '../types/domain'
import './CrmPage.css'

const packages: Record<string, { price: number; hours: number; detail: string }> = {
  'Just Dance & Karaoke Party': {
    price: 420,
    hours: 2,
    detail: '2 horas de fiesta con DJ en vivo, sonido profesional, proyector y ecran, 2 micrófonos inalámbricos, Just Dance, Karaoke y luces inteligentes. No incluye movilidad.',
  },
  'Chicoteca en casa': {
    price: 750,
    hours: 2,
    detail: '2 horas de animación con animador(a) y DJ. Incluye juegos y bailes guiados, luces tipo discoteca y neón, Just Dance o Karaoke, invitación virtual y mini hora loca con globos pencil, pulseras neón y accesorios LED. Movilidad incluida en zonas seleccionadas.',
  },
  'Experiencia Neón': {
    price: 950,
    hours: 3,
    detail: '3 horas de evento: 1 hora de estación Glitter y tatuajes neón + 2 horas de animación con animador(a). Incluye juegos modernos, mini hora loca, invitación virtual, globos pencil, pulseras neón, accesorios LED, DJ y sonido profesional, luces inteligentes y luz UV, proyector gigante para Karaoke y Just Dance, y máquina de humo o burbujas. Movilidad incluida.',
  },
  'Ultra Chicoteca LED': {
    price: 1290,
    hours: 3,
    detail: '3 horas de experiencia: 1 hora de estación Glitter + 2 horas de Animación Chicoteca LED. Incluye pista LED de 3x2 metros, animador(a), Staff (Asistente), DJ, maquilladora, luces inteligentes y láser, proyección láser del nombre, proyector y ecran gigante para Just Dance y Karaoke, juegos de competencia según la edad y mini hora loca LED con globos pencil, pulseras neón, limbo, salta soga y burbujas. Movilidad incluida.',
  },
  'Ultra Chicoteca + Decoración': {
    price: 1590,
    hours: 4,
    detail: '4 horas de experiencia: 1 hora de estación Glitter + 2 horas de animación + 1 hora adicional de DJ, distribuida en 30 minutos antes del evento y 30 minutos después del show. Incluye pista LED de 3x2 metros, animador(a), staff escénico, DJ y maquilladora, juegos exclusivos, proyector y ecran para Just Dance y Karaoke, mini hora loca LED con globos pencil, pulseras neón, limbo y salta soga. Incluye decoración temática base Neón/Glow con backing y cartel neón, 3 mesas acrílicas o cilindros decorativos y accesorios para torta y bocaditos. Movilidad incluida.',
  },
  Personalizado: {
    price: 0,
    hours: 3,
    detail: 'Servicio personalizado de acuerdo con las características y requerimientos del evento.',
  },
}

type FormState = Omit<CrmEvent, 'id' | 'created_at' | 'updated_at'>
const initial: FormState = { cliente: '', agasajado: '', tipo_evento: 'Cumpleaños', edad: null, invitados: null, telefono: '', fecha_evento: new Date().toISOString().slice(0, 10), hora_inicio: '', hora_fin: '', lugar: '', direccion: '', referencia: '', tematica_invitacion: '', cancion_invitacion: '', paquete: 'Personalizado', detalle_servicio: '', juegos_elegidos: '', cronograma: '', adicionales_requerimientos: '', observaciones: '', estado_pago: 'Reservado', total: 0, adelanto: 0, saldo: 0, drive_pdf_url: null }
const money = (value: number) => `S/ ${Number(value || 0).toFixed(2)}`
const balanceOf = (total: number, adelanto: number) => Math.max(0, Number(total || 0) - Number(adelanto || 0))
const dateLabel = (value: string) => value ? new Date(`${value}T12:00:00`).toLocaleDateString('es-PE', { year: 'numeric', month: 'long', day: 'numeric' }) : 'Sin fecha'
const addHours = (time: string, hours: number) => { if (!time) return ''; const [h, m] = time.split(':').map(Number); const minutes = (h * 60 + m + hours * 60) % 1440; return `${String(Math.floor(minutes / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}` }
const splitDetailItems = (value: string) => value.replace(/\r?\n/g, ',').split(/[,;]|\.\s+/).map((item) => item.trim().replace(/^[•\-]\s*/, '')).filter(Boolean)
const splitTimelineItems = (value: string) => value.replace(/\r?\n/g, ',').split(/[,;]+/).map((item) => item.trim().replace(/^[•\-]\s*/, '')).filter(Boolean)

const cleanCaptureKey = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_|_$/g, '')
const captureValue = (map: Record<string, string>, aliases: string[]) => aliases.map(cleanCaptureKey).map((key) => map[key]).find(Boolean)
const matchCapture = (text: string, expression: RegExp) => text.match(expression)?.[1]?.trim()

function parseClientText(text: string): Partial<FormState> {
  const map: Record<string, string> = {}
  const lines = text.split(/\r?\n/).map((line) => line.trim()).filter(Boolean)
  lines.forEach((line) => { const match = line.match(/^([^:–—-]{2,42})\s*[:–—-]\s*(.+)$/); if (match) map[cleanCaptureKey(match[1])] = match[2].trim() })
  const districts = 'Ancón|Ate|Barranco|Breña|Carabayllo|Chaclacayo|Chorrillos|Cieneguilla|Comas|El Agustino|Independencia|Jesús María|La Molina|La Victoria|Lima|Lince|Los Olivos|Lurigancho|Lurín|Magdalena del Mar|Miraflores|Pachacámac|Pucusana|Pueblo Libre|Puente Piedra|Punta Hermosa|Punta Negra|Rímac|San Bartolo|San Borja|San Isidro|San Juan de Lurigancho|San Juan de Miraflores|San Luis|San Martín de Porres|San Miguel|Santa Anita|Santa María del Mar|Santa Rosa|Santiago de Surco|Surquillo|Villa El Salvador|Villa María del Triunfo'
  const phone = captureValue(map, ['telefono', 'celular', 'whatsapp', 'contacto']) || text.match(/(?:\+?51\s*)?(9\d{8})\b/)?.[1]
  const date = captureValue(map, ['fecha_evento', 'fecha del evento', 'fecha', 'dia del evento']) || text.match(/\b\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}\b/)?.[0] || matchCapture(text, /(?:fecha|día)\s*(?:del evento)?\s*(?:es|será|:)?\s*([^\n]+)/i)
  const time = captureValue(map, ['hora_inicio', 'hora', 'horario', 'hora del evento', 'inicio']) || matchCapture(text, /(?:hora|inicio|empieza|será a las)\s*(?:del evento)?\s*(?:es|será|:)?\s*(\d{1,2}(?::\d{2})?\s*(?:a\.?m\.?|p\.?m\.?)?)/i) || text.match(/\b\d{1,2}(?::\d{2})?\s*(?:a\.?m\.?|p\.?m\.?)\b/i)?.[0]
  const address = captureValue(map, ['direccion', 'direccion exacta', 'ubicacion', 'lugar del evento', 'direccion exacta y referencia']) || matchCapture(text, /(?:direcci[oó]n|ubicaci[oó]n|lugar del evento)\s*(?:es|será|:)?\s*([^\n]+)/i)
  const district = captureValue(map, ['distrito', 'distrito del evento', 'lugar']) || text.match(new RegExp(`\\b(${districts})\\b`, 'i'))?.[1]
  const reference = captureValue(map, ['referencia', 'referencia de direccion', 'punto de referencia']) || matchCapture(text, /(?:referencia|ref\.)\s*(?:es|:)?\s*([^\n]+)/i)
  const client = captureValue(map, ['cliente', 'contratante', 'nombre contratante', 'nombre del contratante', 'nombre']) || matchCapture(text, /(?:mi nombre es|soy)\s+([A-Za-zÁÉÍÓÚÜÑáéíóúüñ' .-]{3,80})/i)
  const birthdayPerson = captureValue(map, ['agasajado', 'cumpleanero', 'cumpleañero', 'nombre cumpleanero', 'nombre del cumpleanero', 'festejado']) || matchCapture(text, /(?:cumpleañer[oa]|festejad[oa])\s*(?:se llama|es|:)?\s*([A-Za-zÁÉÍÓÚÜÑáéíóúüñ' .-]{3,80})/i)
  const ageRaw = captureValue(map, ['edad', 'edad del cumpleanero', 'anos', 'años']) || matchCapture(text, /(?:edad|cumple\s*)(?:es|de|:)?\s*(\d{1,2})\s*(?:años|anitos)?/i)
  const song = captureValue(map, ['cancion', 'cancion para invitacion', 'musica', 'musica para invitacion']) || matchCapture(text, /(?:canci[oó]n|m[uú]sica)\s*(?:para (?:la )?invitaci[oó]n)?\s*(?:es|:)?\s*([^\n]+)/i)
  const theme = captureValue(map, ['tematica', 'tematica para invitacion', 'tema', 'tema para invitacion']) || matchCapture(text, /(?:tem[aá]tica|tema)\s*(?:para (?:la )?invitaci[oó]n)?\s*(?:es|:)?\s*([^\n]+)/i)
  const result: Partial<FormState> = {}
  if (client) result.cliente = client; if (phone) result.telefono = phone.replace(/\D/g, '').slice(-9); if (date) result.fecha_evento = normalizeDate(date); if (time) result.hora_inicio = normalizeTime(time); if (address) result.direccion = address; if (district) result.lugar = district; if (reference) result.referencia = reference; if (birthdayPerson) result.agasajado = birthdayPerson; if (ageRaw && Number(ageRaw) > 0) result.edad = Number(ageRaw); if (song) result.cancion_invitacion = song; if (theme) result.tematica_invitacion = theme
  return result
}
function normalizeDate(value?: string) { if (!value) return undefined; const match = value.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/); if (match) return `${match[3].length === 2 ? `20${match[3]}` : match[3]}-${match[2].padStart(2, '0')}-${match[1].padStart(2, '0')}`; const monthNames: Record<string, string> = { enero: '01', febrero: '02', marzo: '03', abril: '04', mayo: '05', junio: '06', julio: '07', agosto: '08', septiembre: '09', setiembre: '09', octubre: '10', noviembre: '11', diciembre: '12' }; const named = value.toLowerCase().match(/(\d{1,2})\s+de\s+([a-záéíóú]+)\s+(?:de\s+)?(\d{4})/); return named && monthNames[named[2].normalize('NFD').replace(/[\u0300-\u036f]/g, '')] ? `${named[3]}-${monthNames[named[2].normalize('NFD').replace(/[\u0300-\u036f]/g, '')]}-${named[1].padStart(2, '0')}` : value }
function normalizeTime(value?: string) { if (!value) return undefined; const match = value.replace(/\./g, '').toLowerCase().match(/^(\d{1,2})(?::(\d{2}))?\s*(am|pm)?$/); if (!match) return value; let hour = Number(match[1]); if (match[3] === 'pm' && hour < 12) hour += 12; if (match[3] === 'am' && hour === 12) hour = 0; return `${String(hour).padStart(2, '0')}:${match[2] || '00'}` }
async function assetToDataUrl(path: string, maxWidth: number, quality = 0.72, background = '#ffffff') {
  const response = await fetch(path)
  if (!response.ok) throw new Error(`No pude cargar ${path}`)
  const objectUrl = URL.createObjectURL(await response.blob())
  try {
    const image = await new Promise<HTMLImageElement>((resolve, reject) => { const element = new Image(); element.onload = () => resolve(element); element.onerror = () => reject(new Error(`No pude leer ${path}`)); element.src = objectUrl })
    const scale = Math.min(1, maxWidth / image.naturalWidth)
    const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(image.naturalWidth * scale)); canvas.height = Math.max(1, Math.round(image.naturalHeight * scale))
    const context = canvas.getContext('2d'); if (!context) throw new Error('No pude preparar la imagen del contrato.')
    context.fillStyle = background; context.fillRect(0, 0, canvas.width, canvas.height); context.drawImage(image, 0, 0, canvas.width, canvas.height)
    return canvas.toDataURL('image/jpeg', quality)
  } finally { URL.revokeObjectURL(objectUrl) }
}
function contractFileName(form: FormState) { const client = form.cliente.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_|_$/g, '') || 'cliente'; return `${form.fecha_evento || 'contrato'}_${client}_MRF.pdf` }

export function CrmPage() {
  const [ready, setReady] = useState(false); const [authenticated, setAuthenticated] = useState(false); const [events, setEvents] = useState<CrmEvent[]>([]); const [form, setForm] = useState<FormState>(initial); const [editingId, setEditingId] = useState<string | null>(null); const [quickText, setQuickText] = useState(''); const [history, setHistory] = useState(false); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>(); const [toasts, setToasts] = useState<ToastMessage[]>([])
  const notify = (title: string, body?: string, kind: ToastMessage['kind'] = 'success') => { const item = { id: Date.now(), title, body, kind }; setToasts((all) => [...all, item]); window.setTimeout(() => setToasts((all) => all.filter((toast) => toast.id !== item.id)), 4200) }
  const load = async () => { const { data, error: loadError } = await requireSupabase().from('crm_events').select('*').order('fecha_evento').order('hora_inicio'); if (loadError) throw loadError; setEvents((data ?? []) as CrmEvent[]) }
  useEffect(() => { if (!supabase) { setReady(true); return }; void supabase.auth.getSession().then(async ({ data }) => { setAuthenticated(Boolean(data.session)); if (data.session) try { await load() } catch (caught) { setError(caught instanceof Error ? `${caught.message}` : 'No se pudo cargar el CRM.') }; setReady(true) }); const { data: listener } = supabase.auth.onAuthStateChange((_type, session) => setAuthenticated(Boolean(session))); return () => listener.subscription.unsubscribe() }, [])
  const visible = useMemo(() => { const today = new Date(); today.setHours(0, 0, 0, 0); return events.filter((item) => { const text = [item.cliente, item.agasajado, item.paquete, item.lugar, item.direccion].join(' ').toLowerCase(); return (!query || text.includes(query.toLowerCase())) && (!status || item.estado_pago === status) && (history || new Date(`${item.fecha_evento}T12:00:00`) >= today) }) }, [events, query, status, history])
  const update = (key: keyof FormState, value: string | number | null) => setForm((current) => { const next = { ...current, [key]: value } as FormState; if (key === 'total' || key === 'adelanto') next.saldo = balanceOf(Number(next.total), Number(next.adelanto)); return next })
  const clear = () => { setForm(initial); setEditingId(null) }
  const captureSmart = () => { const values = parseClientText(quickText); setForm((current) => ({ ...current, ...values, hora_fin: values.hora_inicio ? addHours(values.hora_inicio, packages[current.paquete]?.hours ?? 3) : current.hora_fin })); const captured = Object.keys(values).length; notify(captured ? 'Datos detectados' : 'No reconocí datos', captured ? `${captured} campos completados. Revisa los que falten antes de guardar.` : 'Prueba con un mensaje del cliente o usa la plantilla.') }
  const copyTemplateSmart = () => { void navigator.clipboard.writeText('¡Hola! Para dejar tu reserva lista, por favor envíame estos datos:\n\nNOMBRE DEL CONTRATANTE:\nTELÉFONO:\nDIRECCIÓN EXACTA:\nDISTRITO:\nREFERENCIA:\nFECHA DEL EVENTO: (dd/mm/aaaa)\nHORA DE INICIO: (ej. 6:30 pm)\nNOMBRE DEL CUMPLEAÑERO/A:\nEDAD:\nCANCIÓN PARA LA INVITACIÓN:\nTEMÁTICA PARA LA INVITACIÓN:'); notify('Plantilla copiada', 'El sistema también entiende respuestas escritas a su manera.') }
  const missingContractFields = () => { const fields: string[] = []; if (!form.cliente.trim()) fields.push('nombre del contratante'); if (!form.telefono.trim()) fields.push('teléfono'); if (!form.direccion.trim()) fields.push('dirección exacta'); if (!form.lugar.trim()) fields.push('distrito'); if (!form.referencia.trim()) fields.push('referencia'); if (!form.fecha_evento) fields.push('fecha'); if (!form.hora_inicio) fields.push('hora'); return fields }
  const saveSmart = async (event: FormEvent) => { event.preventDefault(); const missing = missingContractFields(); if (missing.length || form.total <= 0 || form.adelanto > form.total) return notify('Faltan datos para el contrato', missing.length ? missing.join(', ') : 'Revisa el total y el adelanto.', 'error'); setBusy(true); try { const { saldo: _saldo, ...payload } = form; void _saldo; const client = requireSupabase(); const result = editingId ? await client.from('crm_events').update(payload).eq('id', editingId).select('*').single() : await client.from('crm_events').insert(payload).select('*').single(); if (result.error) throw result.error; await load(); setEditingId((result.data as CrmEvent).id); setForm(result.data as CrmEvent); notify(editingId ? 'Reserva actualizada' : 'Reserva guardada') } catch (caught) { notify('No se pudo guardar', caught instanceof Error ? caught.message : 'Revisa los permisos de Supabase.', 'error') } finally { setBusy(false) } }
  const capture = captureSmart
  const copyTemplate = copyTemplateSmart
  const print = async () => {
    const missing = missingContractFields(); if (missing.length) { notify('Contrato incompleto', `Falta: ${missing.join(', ')}.`, 'error'); return }
    try {
      const [headerLogo, watermarkLogo, signature] = await Promise.all([
        assetToDataUrl('/live/mr-fiesta-contract-logo.png', 420, 0.7, '#0d0d12'),
        assetToDataUrl('/live/mr-fiesta-contract-logo.png', 320, 0.62, '#ffffff'),
        assetToDataUrl('/live/firma-andre.png', 360, 0.65),
      ])
      const doc = new jsPDF({ unit: 'mm', format: 'a4' }); const saldo = balanceOf(Number(form.total), Number(form.adelanto)); const number = `MRF-${new Date().toISOString().slice(2, 10).replaceAll('-', '')}-${String(Date.now()).slice(-3)}`
      const footer = (page: number, total: number) => { doc.setFillColor(13, 13, 18); doc.rect(0, 277, 210, 20, 'F'); doc.setTextColor(210, 210, 210); doc.setFontSize(7); doc.text('Web: mrfiesta-pe.github.io  |  Tel: 961 770 164 - 977 783 926  |  mrfiesta.lima@gmail.com', 105, 284, { align: 'center' }); doc.text('Facebook: Mr. Fiesta Lima  |  Instagram: @mrfiesta_lima  |  TikTok: @mrfiesta', 105, 289, { align: 'center' }); doc.text(`Página ${page} de ${total}`, 197, 294, { align: 'right' }) }
      const watermark = () => { const pdf = doc as unknown as { saveGraphicsState: () => void; restoreGraphicsState: () => void; GState: new (options: { opacity: number }) => unknown; setGState: (state: unknown) => void }; try { pdf.saveGraphicsState(); pdf.setGState(new pdf.GState({ opacity: 0.055 })); doc.addImage(watermarkLogo, 'JPEG', 35, 100, 140, 82, 'contract-watermark', 'FAST'); pdf.restoreGraphicsState() } catch { doc.addImage(watermarkLogo, 'JPEG', 72, 130, 66, 39, 'contract-watermark', 'FAST') } }
      const header = (subtitle: string) => { doc.setFillColor(13, 13, 18); doc.rect(0, 0, 210, 40, 'F'); doc.setFillColor(0, 220, 245); doc.rect(0, 38.6, 210, 1.4, 'F'); doc.addImage(headerLogo, 'JPEG', 12, 6, 48, 27, 'contract-header-logo', 'FAST'); doc.setTextColor(255, 47, 146); doc.setFont('helvetica', 'bold'); doc.setFontSize(17); doc.text('MR. FIESTA', 70, 17); doc.setTextColor(0, 220, 245); doc.setFont('helvetica', 'bold'); doc.setFontSize(10.5); doc.text(subtitle.toUpperCase(), 70, 25); doc.setTextColor(178, 184, 195); doc.setFont('helvetica', 'normal'); doc.setFontSize(6.7); doc.text('ENTRETENIMIENTO Y EXPERIENCIAS', 70, 31); doc.text('CÓDIGO DE CONTRATO', 198, 11, { align: 'right' }); doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold'); doc.setFontSize(8.5); doc.text(number, 198, 18, { align: 'right' }) }
      header('Contrato de Prestación de Servicios'); watermark(); doc.setTextColor(35, 35, 35); doc.setFont('helvetica', 'normal'); doc.setFontSize(10); let y = 51
      doc.text(`Fecha de emisión: ${new Date().toLocaleDateString('es-PE')}`, 15, y); y += 9; doc.setFont('helvetica', 'bold'); doc.text('1. DATOS DEL CLIENTE Y EVENTO', 15, y); y += 6; doc.setFont('helvetica', 'normal')
      const rows = [`Cliente / Agasajado: ${form.cliente}${form.agasajado ? ` / ${form.agasajado} (${form.edad || '-'} años)` : ''}`, `Teléfono: ${form.telefono || '-'}`, `Fecha del evento: ${dateLabel(form.fecha_evento)}`, `Horario: Inicio ${form.hora_inicio} - Fin aprox. ${form.hora_fin || '-'}`, `Lugar: ${form.lugar || '-'} - ${form.direccion || '-'}`, `Referencia: ${form.referencia || '-'}`, `Invitación: ${form.tematica_invitacion || '-'} · ${form.cancion_invitacion || '-'}`]
      rows.forEach((row) => { const lines = doc.splitTextToSize(row, 180); doc.text(lines, 15, y); y += lines.length * 4.8 })
      y += 4; doc.setFont('helvetica', 'bold'); doc.text(`2. DETALLES DEL PAQUETE: ${form.paquete.toUpperCase()}`, 15, y); y += 7
      const detailBoxHeight = 100
      doc.setDrawColor(225, 225, 230); doc.roundedRect(15, y, 180, detailBoxHeight, 5, 5, 'S'); doc.setTextColor(255, 47, 146); doc.setFontSize(9.5); doc.setFont('helvetica', 'bold'); doc.text('DETALLE DEL SERVICIO', 20, y + 8); doc.setTextColor(0, 185, 215); doc.text('CRONOGRAMA', 112, y + 8)
      doc.setDrawColor(220, 220, 220); doc.line(106, y + 10, 106, y + detailBoxHeight - 8)
      const serviceItems = splitDetailItems(form.detalle_servicio || 'Servicio de entretenimiento MR FIESTA.')
      let detailY = y + 15; const detailLimit = y + detailBoxHeight - 5; let hiddenServices = 0
      doc.setTextColor(40, 40, 40); doc.setFont('helvetica', 'normal'); doc.setFontSize(6.8)
      serviceItems.forEach((item, index) => { if (hiddenServices) return; const lines = doc.splitTextToSize(item, 77); const itemHeight = Math.max(3.8, lines.length * 3.35 + 0.7); if (detailY + itemHeight > detailLimit) { hiddenServices = serviceItems.length - index; return }; doc.setFillColor(255, 47, 146); doc.circle(21, detailY - 1.15, 0.75, 'F'); doc.text(lines, 24, detailY); detailY += itemHeight })
      if (hiddenServices) { doc.setTextColor(120, 120, 120); doc.setFontSize(6.5); doc.text(`+ ${hiddenServices} servicio(s) indicado(s) en el detalle`, 24, detailLimit - 1) }
      const timeline = splitTimelineItems(form.cronograma || 'Horario por coordinar con el cliente.').slice(0, 7)
      const timelineRows = timeline.map((item) => ({ lines: doc.splitTextToSize(item, 66), height: Math.max(10, doc.splitTextToSize(item, 66).length * 3.9 + 4) }))
      const timelineEnd = Math.min(y + detailBoxHeight - 9, y + 15 + timelineRows.reduce((sum, item) => sum + item.height, 0) - 3)
      if (timelineRows.length) { doc.setDrawColor(0, 205, 225); doc.setLineWidth(1); doc.line(116, y + 15, 116, timelineEnd); doc.setLineWidth(0.2) }
      let timelineY = y + 17; doc.setTextColor(40, 40, 40); doc.setFontSize(7.4)
      timelineRows.forEach((item) => { if (timelineY + item.height > y + detailBoxHeight - 5) return; doc.setFillColor(0, 220, 245); doc.circle(116, timelineY - 1.3, 3.2, 'F'); doc.setFillColor(255, 47, 146); doc.circle(116, timelineY - 1.3, 1.3, 'F'); doc.text(item.lines, 122, timelineY); timelineY += item.height })
      y += detailBoxHeight + 9
      doc.setFillColor(14, 17, 26); doc.roundedRect(15, y, 180, 23, 4, 4, 'F'); doc.setDrawColor(0, 220, 245); doc.roundedRect(15, y, 180, 23, 4, 4, 'S'); doc.setFillColor(255, 47, 146); doc.rect(15, y + 4, 1.4, 15, 'F'); doc.setFont('helvetica', 'bold'); doc.setTextColor(0, 220, 245); doc.setFontSize(8); doc.text('3. CONDICIONES ECONÓMICAS', 21, y + 7); doc.setFont('helvetica', 'normal'); doc.setTextColor(190, 198, 213); doc.setFontSize(7.2); doc.text('COSTO TOTAL', 21, y + 13); doc.text('ADELANTO', 81, y + 13); doc.text('SALDO PENDIENTE', 141, y + 13); doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(255, 255, 255); doc.text(money(form.total), 21, y + 19); doc.text(money(form.adelanto), 81, y + 19); doc.setTextColor(255, 111, 180); doc.text(money(saldo), 141, y + 19); y += 41
      doc.setDrawColor(0, 0, 0); doc.line(25, y, 95, y); doc.line(115, y, 185, y); doc.addImage(signature, 'JPEG', 127, y - 16, 48, 14, 'contract-signature', 'FAST'); doc.setTextColor(30, 30, 30); doc.setFontSize(8.5); doc.text((form.cliente || 'CLIENTE').toUpperCase(), 60, y + 6, { align: 'center' }); doc.text('JOSÉ ANDRÉ HIDALGO A.', 150, y + 6, { align: 'center' }); doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.text('EL CLIENTE', 60, y + 10, { align: 'center' }); doc.text('MR. FIESTA', 150, y + 10, { align: 'center' }); footer(1, 2)
      doc.addPage(); doc.setFillColor(13, 13, 18); doc.rect(0, 0, 210, 15, 'F'); watermark(); doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.text(`ANEXO DE TÉRMINOS Y CONDICIONES - Contrato N° ${number}`, 105, 10, { align: 'center' }); doc.setTextColor(35, 35, 35); doc.setFontSize(11); doc.text('4. TÉRMINOS Y CONDICIONES DEL SERVICIO', 15, 31)
      const clauses = [['1. PAGOS Y CANCELACIONES', 'La reserva se confirma con un pago adelantado. El saldo debe cancelarse el mismo día del evento, antes de instalar los equipos. En caso de anulación por el cliente, la reserva no es reembolsable.'], ['2. PUNTUALIDAD Y EVENTO', 'El tiempo comienza a la hora estipulada en este documento. Se brinda una tolerancia máxima de 10 minutos a favor del cliente para iniciar el show.'], ['3. MOVILIDAD Y LOGÍSTICA', 'La movilidad se rige según el paquete contratado. Si corresponde un distrito alejado o un servicio sin movilidad incluida, el recargo se coordina previamente.'], ['4. OBLIGACIONES DEL CLIENTE', 'El cliente debe proveer energía estable y un espacio seguro. Los daños, robos o extravíos de equipos causados por invitados o condiciones del local serán asumidos por el cliente.']]
      y = 43; clauses.forEach(([title, body]) => { doc.setFont('helvetica', 'bold'); doc.setFontSize(9.5); doc.text(title, 15, y); y += 6; doc.setFont('helvetica', 'normal'); doc.setFontSize(9); const lines = doc.splitTextToSize(body, 180); doc.text(lines, 15, y); y += lines.length * 4.7 + 10 })
      const operationalItems = [['5. JUEGOS ELEGIDOS', form.juegos_elegidos || 'Por definir con el cliente.'], ['6. ADICIONALES Y REQUERIMIENTOS', form.adicionales_requerimientos || 'Sin requerimientos adicionales registrados.']]
      operationalItems.forEach(([title, body]) => { doc.setFillColor(248, 248, 250); doc.setDrawColor(220, 220, 228); const lines = doc.splitTextToSize(body, 168); const height = Math.max(15, lines.length * 4.2 + 10); doc.roundedRect(15, y, 180, height, 3, 3, 'FD'); doc.setTextColor(0, 185, 215); doc.setFont('helvetica', 'bold'); doc.setFontSize(8.4); doc.text(title, 20, y + 6); doc.setTextColor(45, 45, 45); doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.text(lines, 20, y + 11); y += height + 5 })
      footer(2, 2); doc.save(contractFileName(form)); notify('Contrato generado', 'El PDF ya se descargó en tu equipo.')
    } catch (caught) { notify('No pude generar el PDF', caught instanceof Error ? caught.message : 'Revisa los datos e inténtalo de nuevo.', 'error') }
  }
  const whatsapp = () => { const text = `¡Hola ${form.cliente}! 🎉\n\nReserva MR FIESTA\nPaquete: ${form.paquete}\nFecha: ${dateLabel(form.fecha_evento)}\nHora: ${form.hora_inicio}\nLugar: ${form.lugar || '-'}\n\nTotal: ${money(form.total)}\nAdelanto: ${money(form.adelanto)}\nSaldo: ${money(balanceOf(Number(form.total), Number(form.adelanto)))}`; if (form.telefono) window.open(`https://wa.me/51${form.telefono.replace(/\D/g, '')}?text=${encodeURIComponent(text)}`, '_blank', 'noopener,noreferrer') }
  if (!ready) return <main className="loading-screen"><LoaderCircle className="spin" /></main>; if (!supabase) return <AppError />; if (!authenticated) return <Login />; if (error) return <AppError message={error} />
  return (
    <main className="crm-shell">
      <ToastStack messages={toasts} />
      <header className="crm-header"><Link to="/admin" className="admin-brand"><BrandLogo className="admin-logo" /><span>CRM · MR FIESTA</span></Link><div><Link className="crm-nav" to="/admin">LIVE CONTROL</Link><button className="crm-nav-button" onClick={() => void requireSupabase().auth.signOut()}><LogOut size={15} /> Salir</button></div></header>
      <section className="crm-hero"><div className="crm-overview-head"><div><span className="eyebrow">PANEL GENERAL</span><h1>Control de <em>reservas.</em></h1><p>Resumen automático de tus contratos y shows sincronizados.</p></div><div className="crm-status-chips"><span className="reserved">● {events.filter((item) => item.estado_pago === 'Reservado').length} Reservado</span><span className="paid">● {events.filter((item) => item.estado_pago === 'Pagado').length} Pagado</span><span className="pending">● {events.filter((item) => item.estado_pago === 'Pendiente').length} Pendiente</span></div></div><div className="crm-kpi"><article className="crm-metric"><span>Eventos registrados</span><strong>{events.length}</strong></article><article className="crm-metric"><span>Total facturado</span><strong>{money(events.reduce((sum, item) => sum + Number(item.total || 0), 0))}</strong></article><article className="crm-metric"><span>Total adelantado</span><strong>{money(events.reduce((sum, item) => sum + Number(item.adelanto || 0), 0))}</strong></article><article className="crm-metric crm-metric-accent"><span>Saldo pendiente</span><strong>{money(events.reduce((sum, item) => sum + balanceOf(Number(item.total), Number(item.adelanto)), 0))}</strong></article></div></section>
      <section className="crm-layout">
        <form className="crm-form" onSubmit={saveSmart}>
          <div className="crm-title"><div><span className="eyebrow">{editingId ? 'EDITANDO RESERVA' : 'NUEVA RESERVA'}</span><h2>Diseña el show</h2></div>{editingId && <button type="button" className="crm-small" onClick={clear}><X size={14} /> Nueva</button>}</div>
          <section className="crm-capture"><div><b><Clipboard size={15} /> Captura inteligente</b><span>Envía la plantilla, pega la respuesta y completa la reserva en un clic.</span></div><div className="crm-capture-actions"><button type="button" className="crm-small" onClick={copyTemplate}>Copiar plantilla</button><button type="button" className="crm-small crm-small-primary" onClick={capture}>Autocompletar</button></div><textarea value={quickText} onChange={(e) => setQuickText(e.target.value)} placeholder={'CLIENTE: María Pérez\nFECHA_EVENTO: 24/08/2026\nHORA_INICIO: 6:30 pm\nDIRECCION: ...'} /></section>
          <div className="crm-grid three"><Field label="Nombre del contratante"><input value={form.cliente} onChange={(e) => update('cliente', e.target.value)} required /></Field><Field label="Nombre del cumpleañero/a (opcional)"><input value={form.agasajado} onChange={(e) => update('agasajado', e.target.value)} /></Field><Field label="Edad (opcional)"><input type="number" min="1" max="99" value={form.edad ?? ''} onChange={(e) => update('edad', e.target.value ? Number(e.target.value) : null)} /></Field></div>
          <div className="crm-grid three"><Field label="Teléfono"><input value={form.telefono} onChange={(e) => update('telefono', e.target.value)} required /></Field><Field label="Tipo"><select value={form.tipo_evento} onChange={(e) => update('tipo_evento', e.target.value)}><option>Cumpleaños</option><option>Quinceañero</option><option>Promoción</option><option>Baby Shower</option><option>Evento personalizado</option></select></Field><Field label="Fecha"><input type="date" value={form.fecha_evento} onChange={(e) => update('fecha_evento', e.target.value)} required /></Field></div>
          <div className="crm-grid four"><Field label="Inicio"><input type="time" value={form.hora_inicio} onChange={(e) => { update('hora_inicio', e.target.value); if (!form.hora_fin) update('hora_fin', addHours(e.target.value, packages[form.paquete]?.hours ?? 3)) }} required /></Field><Field label="Fin"><input type="time" value={form.hora_fin} onChange={(e) => update('hora_fin', e.target.value)} /></Field><Field label="Distrito"><input value={form.lugar} onChange={(e) => update('lugar', e.target.value)} required /></Field><Field label="Dirección"><input value={form.direccion} onChange={(e) => update('direccion', e.target.value)} required /></Field></div>
          <div className="crm-grid two"><Field label="Dirección exacta"><input value={form.direccion} onChange={(e) => update('direccion', e.target.value)} required /></Field><Field label="Referencia"><input value={form.referencia} onChange={(e) => update('referencia', e.target.value)} placeholder="Ej.: portón negro, frente al parque" required /></Field></div>
          <div className="crm-grid two"><Field label="Canción para la invitación (opcional)"><input value={form.cancion_invitacion} onChange={(e) => update('cancion_invitacion', e.target.value)} /></Field><Field label="Temática para la invitación (opcional)"><input value={form.tematica_invitacion} onChange={(e) => update('tematica_invitacion', e.target.value)} /></Field></div>
          <Field label="Paquete"><select value={form.paquete} onChange={(e) => { const value = e.target.value; update('paquete', value); update('detalle_servicio', packages[value].detail); if (packages[value].price) update('total', packages[value].price); if (!form.hora_fin) update('hora_fin', addHours(form.hora_inicio, packages[value].hours)) }}>{Object.keys(packages).map((item) => <option key={item}>{item}</option>)}</select></Field>
          <section className="crm-experience-panel"><span className="crm-panel-kicker">EXPERIENCIA DEL EVENTO</span><Field label="Detalle del servicio"><textarea value={form.detalle_servicio} onChange={(e) => update('detalle_servicio', e.target.value)} /></Field><Field label="Juegos elegidos"><textarea value={form.juegos_elegidos} onChange={(e) => update('juegos_elegidos', e.target.value)} placeholder="Ej.: Just Dance, Preguntados, Canta y Gana" /></Field><Field label="Cronograma del evento"><textarea value={form.cronograma} onChange={(e) => update('cronograma', e.target.value)} placeholder="Instalación 5:00 pm, Estación Glitter 6:00 pm a 7:00 pm, Show 7:00 pm a 9:00 pm" /></Field><div className="crm-grid two"><Field label="Adicionales / requerimientos"><textarea value={form.adicionales_requerimientos} onChange={(e) => update('adicionales_requerimientos', e.target.value)} placeholder="Ej.: glitter, tatuajes neón, acceso por escalera, 2 personajes" /></Field><Field label="Observaciones internas"><textarea value={form.observaciones} onChange={(e) => update('observaciones', e.target.value)} placeholder="Notas solo para el equipo MR FIESTA" /></Field></div></section>
          <div className="crm-grid three"><Field label="Estado de pago"><select value={form.estado_pago} onChange={(e) => update('estado_pago', e.target.value)}><option>Reservado</option><option>Pendiente</option><option>Pagado</option></select></Field><Field label="Total S/"><input type="number" min="0" step="0.01" value={form.total} onChange={(e) => update('total', Number(e.target.value))} required /></Field><Field label="Adelanto S/"><input type="number" min="0" step="0.01" value={form.adelanto} onChange={(e) => update('adelanto', Number(e.target.value))} /></Field></div>
          <div className="crm-balance">Saldo pendiente <strong>{money(balanceOf(Number(form.total), Number(form.adelanto)))}</strong></div><div className="crm-actions"><button className="primary-button" disabled={busy}>{busy ? <LoaderCircle className="spin" /> : <Save size={16} />} {editingId ? 'Actualizar' : 'Guardar'}</button><button type="button" className="crm-action" onClick={print}><FileText size={16} /> Imprimir / PDF</button><button type="button" className="crm-action" onClick={whatsapp}><MessageCircle size={16} /> WhatsApp</button></div>
        </form>
        <aside className="crm-agenda"><div className="crm-title"><div><span className="eyebrow">AGENDA</span><h2>{history ? 'Historial completo' : 'Próximos shows'}</h2></div><button className="crm-small" onClick={() => setHistory((value) => !value)}>{history ? 'Ver próximos' : 'Ver historial'}</button></div><div className="crm-filters"><input placeholder="Buscar cliente, paquete o distrito" value={query} onChange={(e) => setQuery(e.target.value)} /><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Todos los pagos</option><option>Reservado</option><option>Pendiente</option><option>Pagado</option></select></div>{visible.length ? visible.map((item) => <article className="crm-card" key={item.id}><div className="crm-card-top"><span className={`crm-status ${item.estado_pago.toLowerCase()}`}>{item.estado_pago}</span><span>{dateLabel(item.fecha_evento)}</span></div><h3>{item.cliente}</h3><p><CalendarDays size={13} /> {item.hora_inicio} - {item.hora_fin || '—'} · {item.paquete}</p><p><MapPin size={13} /> {item.lugar || 'Sin distrito'} · {item.direccion || 'Sin dirección'}</p><div className="crm-card-money">Total {money(item.total)} <b>Saldo {money(balanceOf(Number(item.total), Number(item.adelanto)))}</b></div><div className="crm-card-buttons"><button type="button" onClick={() => { const { id, created_at, updated_at, ...values } = item; void created_at; void updated_at; setForm(values); setEditingId(id) }}><Pencil size={13} /> Editar</button><button type="button" onClick={() => { if (window.confirm('¿Eliminar esta reserva?')) void requireSupabase().from('crm_events').delete().eq('id', item.id).then(() => { setEvents((all) => all.filter((entry) => entry.id !== item.id)); notify('Reserva eliminada') }) }}><Trash2 size={13} /> Eliminar</button></div></article>) : <div className="crm-empty">No hay reservas para este filtro.</div>}</aside>
      </section>
    </main>
  )
}

function Login() { const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); const { error } = await requireSupabase().auth.signInWithPassword({ email: String(data.get('email')), password: String(data.get('password')) }); if (error) setMessage('No pudimos iniciar sesión. Revisa tus credenciales.'); setBusy(false) }; return <main className="admin-login"><div className="login-card"><BrandLogo className="login-logo" /><span className="eyebrow">CRM MR FIESTA</span><h1>Entrar al CRM</h1><p>Acceso reservado para administración.</p><form onSubmit={submit}><label>Email<input name="email" type="email" required /></label><label>Contraseña<input name="password" type="password" required /></label>{message && <p className="form-error">{message}</p>}<button className="primary-button" disabled={busy}>{busy ? <LoaderCircle className="spin" /> : 'Entrar'}</button></form></div></main> }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="crm-field">{label}{children}</label> }
