import { type ChangeEvent, type FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Camera, ChevronRight, Flame, Grid2X2, Heart, ImagePlus, LoaderCircle, MessageCircle, Moon, Music2, Plus, Send, Sun, UserRound, X } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { addComment, addReaction, createGuest, createRequest, getEvent, getGuest, getPhotos, getRequests, toggleLike, updateGuest } from '../lib/api'
import { requireSupabase } from '../lib/supabase'
import { AppError } from '../components/AppError'
import { Equalizer } from '../components/Equalizer'
import { StatusPill } from '../components/StatusPill'
import { ToastStack } from '../components/ToastStack'
import { BrandLogo } from '../components/BrandLogo'
import type { Event, Guest, Photo, SongRequest, ToastMessage } from '../types/domain'
import { compressImage } from '../utils/images'

type Tab = 'music' | 'gallery' | 'top' | 'profile'
const guestKey = (slug: string) => `mrfiesta:guest:${slug}`

export function GuestPage() {
  const { slug = '' } = useParams()
  const [event, setEvent] = useState<Event>(); const [guest, setGuest] = useState<Guest>(); const [requests, setRequests] = useState<SongRequest[]>([])
  const [photos, setPhotos] = useState<Photo[]>([]); const [tab, setTab] = useState<Tab>('music'); const [light, setLight] = useState(() => localStorage.getItem('mrfiesta:theme') === 'light')
  const [sheet, setSheet] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [toasts, setToasts] = useState<ToastMessage[]>([])
  const notify = useCallback((title: string, body?: string, kind: ToastMessage['kind'] = 'success') => { const item = { id: Date.now(), title, body, kind }; setToasts((current) => [...current, item]); window.setTimeout(() => setToasts((current) => current.filter((toast) => toast.id !== item.id)), 4600) }, [])
  const loadRequests = useCallback(async (eventId: string) => setRequests(await getRequests(eventId)), [])
  const loadPhotos = useCallback(async (eventId: string, guestId: string) => setPhotos(await getPhotos(eventId, guestId)), [])

  useEffect(() => { let alive = true; (async () => { try { const loaded = await getEvent(slug); if (!alive) return; setEvent(loaded); const savedId = localStorage.getItem(guestKey(slug)); if (savedId) { const savedGuest = await getGuest(savedId); if (alive) { setGuest(savedGuest); await Promise.all([loadRequests(loaded.id), loadPhotos(loaded.id, savedGuest.id)]) } } } catch (caught) { if (alive) setError(caught instanceof Error ? caught.message : 'No se pudo abrir el evento.') } finally { if (alive) setLoading(false) } })(); return () => { alive = false } }, [slug, loadPhotos, loadRequests])

  useEffect(() => { if (!event || !guest) return; const client = requireSupabase(); const refresh = () => { void Promise.all([loadRequests(event.id), loadPhotos(event.id, guest.id)]) }; const channel = client.channel(`event-${event.id}-guest-${guest.id}`).on('postgres_changes', { event: '*', schema: 'public', table: 'song_requests', filter: `event_id=eq.${event.id}` }, refresh).on('postgres_changes', { event: '*', schema: 'public', table: 'song_votes', filter: `event_id=eq.${event.id}` }, refresh).on('postgres_changes', { event: '*', schema: 'public', table: 'photos', filter: `event_id=eq.${event.id}` }, refresh).on('postgres_changes', { event: '*', schema: 'public', table: 'photo_likes', filter: `event_id=eq.${event.id}` }, refresh).on('postgres_changes', { event: '*', schema: 'public', table: 'photo_reactions', filter: `event_id=eq.${event.id}` }, refresh).subscribe(); return () => { void client.removeChannel(channel) } }, [event, guest, loadPhotos, loadRequests])

  const currentPlaying = requests.find((request) => request.status === 'playing')
  const currentPlayingId = currentPlaying?.id
  useEffect(() => { if (currentPlayingId) notify('🔥 ¡Hay música en vivo!', 'Mira la tarjeta EN VIVO para ver qué está sonando.', 'info') }, [currentPlayingId, notify])

  const switchTheme = () => { setLight((current) => { localStorage.setItem('mrfiesta:theme', current ? 'dark' : 'light'); return !current }) }
  if (loading) return <main className="loading-screen"><LoaderCircle className="spin" /><span>Preparando tu fiesta…</span></main>
  if (error || !event) return <AppError message={error} />
  if (!guest) return <Onboarding event={event} slug={slug} onDone={async (created) => { setGuest(created); await Promise.all([loadRequests(event.id), loadPhotos(event.id, created.id)]) }} light={light} switchTheme={switchTheme} />
  const playing = currentPlaying
  return <main className={`guest-shell ${light ? 'light' : ''}`}><ToastStack messages={toasts} /><header className="guest-header"><div className="brand-row"><BrandLogo className="guest-logo" /><div><strong>LIVE EXPERIENCE</strong><small>{event.name}</small></div></div><button className="theme-toggle" onClick={switchTheme} aria-label="Cambiar tema">{light ? <Moon /> : <Sun />}</button></header>
    <section className="guest-content">
      {tab === 'music' && <MusicTab event={event} guest={guest} requests={requests} playing={playing} onRequest={async (values) => { await createRequest(event, guest, values); await loadRequests(event.id); notify('¡Enviado a cabina!', 'El DJ ha recibido tu pedido.') }} />}
      {tab === 'gallery' && <GalleryTab event={event} photos={photos} onLike={async (photo) => { await toggleLike(photo, guest.id); await loadPhotos(event.id, guest.id) }} onReact={async (photo, reaction) => { await addReaction(photo, guest.id, reaction); await loadPhotos(event.id, guest.id) }} onComment={async (photo, content) => { await addComment(photo, guest, content); notify('Comentario enviado', 'Ya forma parte de la conversación.') }} />}
      {tab === 'top' && <TopTab requests={requests} guest={guest} event={event} refresh={() => loadRequests(event.id)} />}
      {tab === 'profile' && <ProfileTab event={event} guest={guest} requests={requests} photos={photos} onSaved={async (name, table) => { const updated = await updateGuest(guest.id, name, table); setGuest(updated); notify('Perfil actualizado', 'Tu identidad en esta fiesta está al día.') }} onExit={() => { localStorage.removeItem(guestKey(slug)); setGuest(undefined); setRequests([]); setPhotos([]) }} />}
    </section>
    <nav className="mobile-nav"><NavButton active={tab === 'music'} icon={<Music2 />} label="Música" onClick={() => setTab('music')} /><NavButton active={tab === 'gallery'} icon={<Grid2X2 />} label="Galería" onClick={() => setTab('gallery')} /><button className="plus-button" onClick={() => setSheet(true)} aria-label="Crear"><Plus /></button><NavButton active={tab === 'top'} icon={<Flame />} label="Top" onClick={() => setTab('top')} /><NavButton active={tab === 'profile'} icon={<UserRound />} label="Perfil" onClick={() => setTab('profile')} /></nav>
    {sheet && <CreateSheet onClose={() => setSheet(false)} onMusic={() => { setSheet(false); setTab('music'); document.getElementById('song-field')?.focus() }} onFile={async (file) => { try { const compact = await compressImage(file); const ext = compact.name.split('.').pop() || 'jpg'; const path = `${event.id}/${guest.id}/${crypto.randomUUID()}.${ext}`; const client = requireSupabase(); const { error: uploadError } = await client.storage.from('event-photos').upload(path, compact, { contentType: compact.type, upsert: false }); if (uploadError) throw uploadError; const moderation = event.theme?.gallery_moderation === 'manual' ? 'pending' : 'published'; const { error: insertError } = await client.from('photos').insert({ event_id: event.id, guest_id: guest.id, guest_name: guest.display_name, storage_path: path, status: moderation }); if (insertError) throw insertError; await loadPhotos(event.id, guest.id); setSheet(false); notify(moderation === 'published' ? '¡Foto publicada!' : 'Foto enviada a revisión', moderation === 'published' ? 'Tu recuerdo ya está en la galería.' : 'La publicaremos apenas sea aprobada.'); } catch { notify('No se pudo subir la foto', 'Prueba de nuevo con una imagen más pequeña.', 'error') } }} />}
  </main>
}

function Onboarding({ event, slug, onDone, light, switchTheme }: { event: Event; slug: string; onDone: (guest: Guest) => Promise<void>; light: boolean; switchTheme: () => void }) { const [name, setName] = useState(''); const [table, setTable] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const submit = async (form: FormEvent) => { form.preventDefault(); if (name.trim().length < 2) return setMessage('Escribe un nombre o apodo de al menos 2 caracteres.'); setBusy(true); try { const guest = await createGuest(event.id, name, table); localStorage.setItem(guestKey(slug), guest.id); await onDone(guest) } catch { setMessage('No pudimos conectarte. Revisa tu conexión e inténtalo otra vez.') } finally { setBusy(false) } }; return <main className={`onboarding ${light ? 'light' : ''}`}><header className="guest-header"><div className="brand-row"><BrandLogo className="guest-logo" /><div><strong>LIVE EXPERIENCE</strong><small>{event.name}</small></div></div><button className="theme-toggle" onClick={switchTheme}>{light ? <Moon /> : <Sun />}</button></header><div className="onboarding-card"><span className="eyebrow">{event.event_date}</span><h1>La noche empieza contigo.</h1><p>Bienvenido a <strong>{event.name}</strong>. Dinos quién eres y conéctate con la cabina.</p><form onSubmit={submit}><label>Tu nombre o apodo <b>*</b><input value={name} maxLength={48} placeholder="Ej. André" onChange={(input) => setName(input.target.value)} autoFocus /></label><label>N° de mesa <span>(opcional)</span><input value={table} maxLength={20} placeholder="Ej. Mesa 5" onChange={(input) => setTable(input.target.value)} /></label>{message && <p className="form-error">{message}</p>}<button className="primary-button" disabled={busy}>{busy ? <LoaderCircle className="spin" /> : <>Conectarse a la fiesta <ChevronRight /></>}</button></form></div></main> }

function MusicTab({ event, guest, requests, playing, onRequest }: { event: Event; guest: Guest; requests: SongRequest[]; playing?: SongRequest; onRequest: (values: { song: string; artist: string; dedication: string }) => Promise<void> }) { const [song, setSong] = useState(''); const [artist, setArtist] = useState(''); const [dedication, setDedication] = useState(''); const [busy, setBusy] = useState(false); const mine = requests.filter((request) => request.guest_id === guest.id); const submit = async (form: FormEvent) => { form.preventDefault(); if (!song.trim()) return; setBusy(true); try { await onRequest({ song, artist, dedication }); setSong(''); setArtist(''); setDedication('') } finally { setBusy(false) } }; return <><section className="hero-copy"><span className="eyebrow">{event.celebrant_name ? `Celebramos a ${event.celebrant_name}` : 'Fiesta en vivo'}</span><h1>El DJ está <em>escuchando.</em></h1></section>{playing ? <article className="now-playing"><span className="live-dot">EN VIVO</span><div className="disc" /><div className="track-copy"><strong>{playing.song_title}</strong><small>{playing.artist || 'Solicitud de la fiesta'}</small>{playing.dedication && <span>Para: {playing.dedication}</span>}</div><Equalizer />{playing.table_number && <div className="table-tag">Pedido para {playing.table_number}</div>}</article> : <article className="empty-live"><Music2 /><div><strong>La pista espera su próximo himno</strong><span>Envía una canción al DJ para empezar.</span></div></article>}<section className="request-card"><div className="section-title"><Music2 /><div><h2>Pide una canción</h2><p>Tu solicitud llega en tiempo real.</p></div></div><form onSubmit={submit}><label>¿Qué quieres escuchar?<input id="song-field" value={song} maxLength={100} placeholder="Canción o artista" onChange={(input) => setSong(input.target.value)} /></label><label>Artista <span>(opcional)</span><input value={artist} maxLength={100} placeholder="¿Quién la canta?" onChange={(input) => setArtist(input.target.value)} /></label><label>Dedicatoria <span>(opcional)</span><input value={dedication} maxLength={180} placeholder="Para alguien especial…" onChange={(input) => setDedication(input.target.value)} /></label><button className="primary-button" disabled={busy || !song.trim()}>{busy ? <LoaderCircle className="spin" /> : <><Send /> Enviar a cabina</>}</button></form></section><section className="my-requests"><div className="section-heading"><h2>Tus pedidos</h2><span>{mine.length}</span></div>{mine.length ? mine.map((request) => <article className="request-row" key={request.id}><Music2 /><div><strong>{request.song_title}</strong><small>{request.artist || 'Artista no indicado'}</small></div><StatusPill status={request.status} /></article>) : <div className="empty-state"><Music2 /><p>Aún no has enviado canciones. El DJ está listo.</p></div>}</section></> }

function GalleryTab({ event, photos, onLike, onReact, onComment }: { event: Event; photos: Photo[]; onLike: (photo: Photo) => Promise<void>; onReact: (photo: Photo, reaction: string) => Promise<void>; onComment: (photo: Photo, value: string) => Promise<void> }) { const [commentFor, setCommentFor] = useState<string>(); const [comment, setComment] = useState(''); return <><section className="hero-copy compact"><span className="eyebrow">MR FIESTA LIVE GALLERY</span><h1>Recuerdos que <em>pasan ahora.</em></h1></section>{photos.length ? <section className="photo-feed">{photos.map((photo) => <article className="photo-post" key={photo.id}><img src={photo.public_url} alt={photo.caption || `Foto compartida por ${photo.guest_name}`} /><div className="post-body"><div className="post-head"><strong>{photo.guest_name}</strong><time>{new Date(photo.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div>{photo.caption && <p>{photo.caption}</p>}<div className="reaction-line">{['🔥', '🎉', '🙌', '💃', '💖'].map((reaction) => <button key={reaction} onClick={() => void onReact(photo, reaction)}>{reaction}{photo.reactions?.[reaction] ? <small>{photo.reactions[reaction]}</small> : null}</button>)}</div><div className="post-actions"><button className={photo.likedByMe ? 'liked' : ''} onClick={() => void onLike(photo)}><Heart fill={photo.likedByMe ? 'currentColor' : 'none'} /> {photo.likes || 0} Me gusta</button><button onClick={() => setCommentFor(photo.id)}><MessageCircle /> Comentar</button></div>{commentFor === photo.id && <form className="comment-form" onSubmit={(form) => { form.preventDefault(); if (comment.trim()) { void onComment(photo, comment); setComment(''); setCommentFor(undefined) } }}><input value={comment} maxLength={300} placeholder="Escribe un comentario" onChange={(input) => setComment(input.target.value)} autoFocus /><button><Send /></button></form>}</div></article>)}</section> : <div className="empty-state tall"><ImagePlus /><h2>La galería está esperando</h2><p>Comparte el primer recuerdo de {event.name} tocando el botón +.</p></div>}</> }

function TopTab({ event, guest, requests, refresh }: { event: Event; guest: Guest; requests: SongRequest[]; refresh: () => Promise<void> }) { const top = useMemo(() => [...requests].filter((request) => request.status !== 'rejected').sort((a, b) => (b.votes ?? 0) - (a.votes ?? 0) || (a.status === 'playing' ? -1 : 0) - (b.status === 'playing' ? -1 : 0)), [requests]); const vote = async (request: SongRequest) => { try { const { error } = await requireSupabase().from('song_votes').insert({ event_id: event.id, song_request_id: request.id, guest_id: guest.id }); if (error?.code === '23505') return; if (error) throw error; await refresh() } catch { /* RLS / duplicate state is intentionally silent for this small action */ } }; return <><section className="hero-copy compact"><span className="eyebrow">MR FIESTA LIVE TOP</span><h1>Lo que la fiesta <em>quiere oír.</em></h1></section><section className="top-list">{top.length ? top.map((request, index) => <article key={request.id} className="top-row"><b>#{index + 1}</b><div><strong>{request.song_title}</strong><small>{request.artist || request.guest_name}</small></div><button onClick={() => void vote(request)}><Flame /> {request.votes || 0}</button></article>) : <div className="empty-state"><Flame /><p>Las canciones más votadas aparecerán aquí.</p></div>}</section></> }

function ProfileTab({ event, guest, requests, photos, onSaved, onExit }: { event: Event; guest: Guest; requests: SongRequest[]; photos: Photo[]; onSaved: (name: string, table: string) => Promise<void>; onExit: () => void }) { const [name, setName] = useState(guest.display_name); const [table, setTable] = useState(guest.table_number || ''); return <><section className="profile-hero"><div className="avatar">{guest.display_name.slice(0, 1).toUpperCase()}</div><div><span className="eyebrow">Invitado</span><h1>{guest.display_name}</h1><p>{event.name}{guest.table_number ? ` · ${guest.table_number}` : ''}</p></div></section><section className="stats"><div><b>{requests.length}</b><span>Canciones</span></div><div><b>{photos.filter((photo) => photo.guest_id === guest.id).length}</b><span>Fotos</span></div><div><b>{photos.filter((photo) => photo.guest_id === guest.id).reduce((sum, photo) => sum + (photo.likes || 0), 0)}</b><span>Likes</span></div></section><section className="request-card"><div className="section-title"><UserRound /><div><h2>Tu perfil</h2><p>Solo cambia cómo te ve esta fiesta.</p></div></div><label>Nombre<input value={name} maxLength={48} onChange={(input) => setName(input.target.value)} /></label><label>Mesa<input value={table} maxLength={20} onChange={(input) => setTable(input.target.value)} /></label><button className="secondary-button" onClick={() => void onSaved(name, table)}>Guardar cambios</button><button className="ghost-danger" onClick={onExit}>Salir del evento</button></section></> }

function CreateSheet({ onClose, onMusic, onFile }: { onClose: () => void; onMusic: () => void; onFile: (file: File) => Promise<void> }) { const select = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) void onFile(file) }; return <div className="sheet-backdrop" onClick={onClose}><section className="create-sheet" onClick={(event) => event.stopPropagation()}><button className="sheet-close" onClick={onClose}><X /></button><div className="sheet-handle" /><h2>¿Qué vamos a crear?</h2><div className="create-options"><button onClick={onMusic}><Music2 /><span>Pedir<br />canción</span></button><label><Camera /><span>Tomar<br />foto</span><input type="file" accept="image/*" capture="environment" onChange={select} /></label><label><ImagePlus /><span>Subir<br />galería</span><input type="file" accept="image/*" onChange={select} /></label></div></section></div> }
function NavButton({ active, icon, label, onClick }: { active: boolean; icon: React.ReactNode; label: string; onClick: () => void }) { return <button className={active ? 'active' : ''} onClick={onClick}>{icon}<span>{label}</span></button> }
