const SUPABASE_URL='https://jejskqoserveuzstqjgg.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_XDLNumdR0AM4NF8ACor3ng_nLEI7SIf';
const _supabase=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const APPS_SCRIPT_URL='https://script.google.com/macros/s/AKfycbxAo1Tx4ndMC7LNKX6w-_9aCrvGvWfzvmpUxGW5aATeZJ4d4bB3OaOE9Vvp_8VBa9c/exec';
let listaClientesGlobal=[],seleccionesPorGaleria={};const $=s=>document.querySelector(s);
function escapeHtml(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;$('#toast-stack').append(e);setTimeout(()=>e.remove(),3600)}
async function cargarClientes(){const [{data,error},{data:selecciones}]=await Promise.all([_supabase.from('galerias').select('*').order('id',{ascending:false}),_supabase.from('selecciones').select('galeria_id')]);if(error){$('#lista-galerias').innerHTML='<div class="empty">No se pudieron cargar las galerías.</div>';toast(error.message);return}seleccionesPorGaleria=(selecciones||[]).reduce((a,x)=>(a[x.galeria_id]=(a[x.galeria_id]||0)+1,a),{});listaClientesGlobal=data||[];actualizarKpis();renderizarTabla();}
function actualizarKpis(){const total=listaClientesGlobal.length,aprobadas=listaClientesGlobal.filter(x=>x.aprobado===true).length,pending=total-aprobadas,selecciones=Object.values(seleccionesPorGaleria).reduce((a,b)=>a+b,0);$('#kpi-total').textContent=total;$('#kpi-pendientes').textContent=pending;$('#kpi-aprobadas').textContent=aprobadas;$('#kpi-selecciones').textContent=selecciones}
function renderizarTabla(){const texto=$('#buscador').value.toLowerCase(),filtro=$('#filtro-estado').value;const clientes=listaClientesGlobal.filter(c=>c.client_name.toLowerCase().includes(texto)&&(filtro==='todos'||(filtro==='aprobado'?c.aprobado===true:c.aprobado!==true)));const list=$('#lista-galerias');if(!clientes.length){list.innerHTML='<div class="empty">No encontramos galerías con esos filtros.</div>';return}list.innerHTML='';clientes.forEach(item=>{const aprobado=item.aprobado===true,seleccionadas=seleccionesPorGaleria[item.id]||0,card=document.createElement('article');card.className='gallery-card';card.innerHTML=`<div class="card-art"><span>${aprobado?'Entrega lista':'Selección privada'}</span></div><h3 class="card-title">${escapeHtml(item.client_name)}</h3><div class="card-slug">?galeria=${escapeHtml(item.slug)}</div><div class="card-data"><span class="pill">${seleccionadas} seleccionadas</span><span class="pill">Límite ${item.limite_fotos||100}</span><span class="pill ${aprobado?'approved':'pending'}">${aprobado?'Descarga activa':'Pendiente'}</span></div><div class="card-actions"><a href="index.html?galeria=${encodeURIComponent(item.slug)}" target="_blank" title="Ver galería"><i data-lucide="external-link" size="14"></i></a><button data-action="limit" title="Editar límite"><i data-lucide="sliders-horizontal" size="14"></i></button><button data-action="watermark" title="Marca de agua"><i data-lucide="${item.con_marca_agua!==false?'shield-check':'shield-off'}" size="14"></i></button><button data-action="approval" class="approve">${aprobado?'Bloquear':'Aprobar'}</button><button data-action="delete" class="danger" title="Eliminar"><i data-lucide="trash-2" size="14"></i></button></div>`;card.querySelector('[data-action="limit"]').onclick=()=>cambiarLimite(item.id,item.limite_fotos||100);card.querySelector('[data-action="watermark"]').onclick=()=>toggleMarcaAgua(item.id,item.con_marca_agua!==false);card.querySelector('[data-action="approval"]').onclick=()=>toggleAprobacion(item.id,aprobado);card.querySelector('[data-action="delete"]').onclick=()=>eliminarCliente(item.id);list.append(card)});lucide.createIcons()}
async function cambiarLimite(id,actual){const valor=prompt('Nuevo límite de fotografías:',actual);if(valor===null||!Number.isInteger(Number(valor))||Number(valor)<1){if(valor!==null)toast('Ingresa un número válido mayor que cero.');return}const {error}=await _supabase.from('galerias').update({limite_fotos:parseInt(valor)}).eq('id',id);if(error)toast(error.message);else{toast('Límite actualizado.');cargarClientes()}}
async function toggleMarcaAgua(id,actual){const {error}=await _supabase.from('galerias').update({con_marca_agua:!actual}).eq('id',id);if(error)toast(error.message);else{toast(!actual?'Marca de agua activada.':'Marca de agua desactivada.');cargarClientes()}}
async function toggleAprobacion(id,actual){const mensaje=actual?'¿Bloquear temporalmente la descarga?':'¿Aprobar la selección y habilitar la descarga?';if(!confirm(mensaje))return;const {error}=await _supabase.from('galerias').update({aprobado:!actual}).eq('id',id);if(error)toast(error.message);else{toast(!actual?'Descarga habilitada.':'Descarga bloqueada.');cargarClientes()}}
async function eliminarCliente(id){if(!confirm('¿Eliminar este registro de la base de datos? Esta acción no borra su carpeta de Drive.'))return;const {error}=await _supabase.from('galerias').delete().eq('id',id);if(error)toast(error.message);else{toast('Galería eliminada.');cargarClientes()}}
function abrirModal(){const m=$('#modal-cliente');m.classList.add('open');m.setAttribute('aria-hidden','false');$('#nombreCliente').focus()}function cerrarModal(){$('#modal-cliente').classList.remove('open');$('#modal-cliente').setAttribute('aria-hidden','true')}
async function crearClienteAutomatico(e){e.preventDefault();const nombre=$('#nombreCliente').value.trim(),limite=parseInt($('#limiteFotos').value)||100,conMarca=$('#conMarcaAgua').checked,slug=nombre.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'-').replace(/-+/g,'-');if(!nombre)return;const btn=$('#btn-guardar');btn.textContent='Creando…';btn.disabled=true;try{const res=await fetch(`${APPS_SCRIPT_URL}?action=crearCarpeta&nombre=${encodeURIComponent(nombre)}`),resultado=await res.json();if(!resultado.success){toast(`No se creó la carpeta: ${resultado.error}`);return}const {error}=await _supabase.from('galerias').insert([{client_name:nombre,slug,folder_id:resultado.folderId,limite_fotos:limite,aprobado:false,con_marca_agua:conMarca}]);if(error)toast(`No se guardó: ${error.message}`);else{cerrarModal();e.target.reset();$('#limiteFotos').value=100;$('#conMarcaAgua').checked=true;toast('Galería creada y lista para usar.');cargarClientes()}}catch(err){console.error(err);toast('No se pudo conectar con el servidor.')}finally{btn.innerHTML='<i data-lucide="plus" size="17"></i> Crear galería';btn.disabled=false;lucide.createIcons()}}
$('#abrir-modal').onclick=abrirModal;$('#cerrar-modal').onclick=cerrarModal;$('#modal-cliente').addEventListener('click',e=>{if(e.target===$('#modal-cliente'))cerrarModal()});$('#form-nuevo-cliente').addEventListener('submit',crearClienteAutomatico);$('#buscador').addEventListener('input',renderizarTabla);$('#filtro-estado').addEventListener('change',renderizarTabla);lucide.createIcons();cargarClientes();
